-- MySQL Script generated by MySQL Workbench
-- 05/25/15 08:48:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema YEnterprises
-- -----------------------------------------------------
-- 
-- 
DROP SCHEMA IF EXISTS `YEnterprises` ;

-- -----------------------------------------------------
-- Schema YEnterprises
--
-- 
-- 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `YEnterprises` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `YEnterprises` ;

-- -----------------------------------------------------
-- Table `YEnterprises`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `YEnterprises`.`user` ;

CREATE TABLE IF NOT EXISTS `YEnterprises`.`user` (
  `userid` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` DATETIME  DEFAULT CURRENT_TIMESTAMP NULL,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  PRIMARY KEY (`userid`));


-- -----------------------------------------------------
-- Table `YEnterprises`.`post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `YEnterprises`.`post` ;

CREATE TABLE IF NOT EXISTS `YEnterprises`.`post` (
  `postId` INT NOT NULL AUTO_INCREMENT,
  `createdate` DATETIME NOT NULL,
  `createdby` VARCHAR(20) NOT NULL,
  `title` VARCHAR(20) NOT NULL,
  `shortdesc` VARCHAR(30) NOT NULL,
  `longdesc` VARCHAR(500) NULL,
  `updatedby` VARCHAR(20) NULL,
  `updateddate` DATETIME NULL,
  PRIMARY KEY (`postId`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
